[book]
language = "en"
multilingual = false
title = "nekos.best API"
description = "The official nekos.best API documentation."

[output.html]
cname = "docs.nekos.best"

default-theme = "nekosbest"
preferred-dark-theme = "nekosbest"

git-repository-icon = "fa-github"
git-repository-url = "https://github.com/nekos-best/docs"

[output.html.search]
limit-results = 10

[output.html.print]
enable = false
