[book]
language = "en"
multilingual = false
title = "Neko Bot Docs"
description = "The official nekos.best API documentation."

[output.html]
cname = "docs.kori-vr.live"

default-theme = "neko"
preferred-dark-theme = "neko"

git-repository-icon = "fa-github"
git-repository-url = "https://github.com/korivirtual/docs"

[output.html.search]
limit-results = 10

[output.html.print]
enable = false
